name: workflow.yml
on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: my-docker-image

jobs:
    build:
        name: Build and Push Docker Image
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            security-events: write

        steps:
            -   uses: actions/checkout@v6

            -   name: Set up Java
                uses: actions/setup-java@v5
                with:
                    distribution: 'temurin'
                    java-version: '21'

            -   name: Cache Gradle packages
                uses: actions/cache@v4
                with:
                    key: ~/.gradle/caches
                    path: $ {{runner.os}}-gradle-caches-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                    restore-keys: ${{ runner.os }}-gradle

            -   name: Make gradlew executable
                run: chmod +x ./demo/gradlew

            -   name: Build with Gradle
                run: |
                    cd ./demo
                    ./gradlew clean bootJar --no-daemon

            -   name: Log in to Container Registry
                uses: docker/login-action@v3
                with:
                    registry: ${{ env.REGISTRY }}
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Build and push Docker image
                run: |
                    cd ./demo
                    ./gradlew --no-daemon bootBuildImage \
                        --imageName=${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest \

            -   name: Push Docker image to registry
                run: |
                    docker push ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
    tests:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v6

            -   name: Set up Java
                uses: actions/setup-java@v5
                with:
                    distribution: 'temurin'
                    java-version: '21'

            -   name: Cache Gradle packages
                uses: actions/cache@v4
                with:
                    path: ~/.gradle/caches
                    key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                    restore-keys: ${{ runner.os }}-gradle

            -   name: Make gradlew executable
                run: chmod +x ./demo/gradlew

            -   name: Run tests with Gradle
                run: |
                    cd ./demo
                    ./gradlew test --no-daemon

            -   name: Verify JaCoCo coverage
                run: |
                    cd ./demo
                    ./gradlew jacocoTestCoverageVerification --no-daemon
                continue-on-error: true

#            -   name: Upload coverage to Codecov
#                uses: codecov/codecov-action@v5
#                with:
#                    files: ./demo/build/reports/jacoco/test/jacocoTestReport.xml
#                    flags: unittests
#                    name: codecov-umbrella
#                    fail_ci_if_error: false

            -   name: Upload JaCoCo HTML Report
                uses: actions/upload-artifact@v5
                if: always()
                with:
                    name: jacoco-report
                    path: demo/build/reports/jacoco/test/html/
#    TODO: Add security scan + production deployment